### ISSUE TITLE
Download quickstart code?

### ISSUE THREAD

**Issue by bfrey** [lore/lore#154] opened 2017-02-09 18:47 UTC
I was following along in the quickstart to build the twitter clone, and something went wrong. I have tried backing out the recent changes but it still hangs on Loading. Is there a place to download the code to completed tutorial so I can verify what broke? 

Console shows no errors except:
ReferenceError: PropTypes is not defined[Learn More]  bundle.js%20line%202584%20%3E%20eval:1

**Comment by jchansen** [comment] 2017-02-09 20:50
@bfrey not currently, but I can upload a repo that captures the final version of the application tonight. What is your language preference? ES5, ES6 or ESNext? I'll set it up to match.

Also what step are you currently on? I'll inspect for typos as well.

**Comment by bfrey** [comment] 2017-02-09 20:55
That would be fantastic! I was using the ES5 code. I made it up to this step:

http://www.lorejs.org/quickstart/authorization/step-2/

I'm running on windows 7 64bit. Even before it completely failed with the Loading screen, it took a significant amount of time to re-load after each change. Like 30seconds or more to load the UI and get requests from the json server. Have you seen that before? Is it a windows artifact?

**Comment by jchansen** [comment] 2017-02-09 21:06
@bfrey hmm...no, I haven't seen that before. I usually work on a Mac, but I have a Windows 10 computer at home. I'll run through the tutorial on that and see if I end up replicating your issue.

Would you be willing to upload the code you have to GitHub? I can clone the repo and investigate.

**Comment by jchansen** [comment] 2017-02-10 09:18
@bfrey I created a repository for the ES5 version of the Quickstart. You can find that repository here:

https://github.com/lore/lore-quickstart-es5

### Instructions for using Quickstart Repo
Each step has a corresponding branch, so that you can check out the finished code on a per-step basis. For example, to clone the repo and checkout the finished code the step 2 of the Authorization section, you can run these commands:

```sh
git clone git@github.com:lore/lore-quickstart-es5.git
git checkout authorization.2
```

Thanks for raising this issue. I'm glad you did. I'll be creating repos for the ES6 and ESNext versions of the Quickstart as well, and will incorporate an instruction within the Quickstart itself on what command to run to switch to the branch with the finished code. I'll work on that this weekend.

### Windows Runthrough (postponed until this weekend)
Unfortunately, I wasn't able to run through the Quickstart on my Windows 10 machine, as I had an issue with my monitor and couldn't get it to display anything : ( But I'll resolve the monitor issue tomorrow and will follow up with you this weekend about whether I find any Windows-specific issues.

### Issue Found in Step 1 of Authorization Section
That being said, I did notice one issue in step 1 of the Authorization section that may have contributed to your issue. I wrote an incorrect import statement in the instruction, which you can [see fixed in this commit](https://github.com/lore/www.lorejs.org/commit/11a5e43b7995d8f779147053b41cc92ba2888ec6). The `require` statement for the `AuthorizationGenerator` generator was written like this:

```js
var AuthorizationGenerator = require('lore-auth');
```

when it should have been this:

```js
var AuthorizationGenerator = require('lore-auth').AuthorizationGenerator;
```

Let me know if you have any further issues with the Quickstart or suggestions for improvement. Thanks again for bringing this up!

**Comment by bfrey** [comment] 2017-02-10 16:26
Thank you so much for doing this. I did get a bit further. I got as far as installing Sails and working through the Server->Add Auth Header. At that point it got stuck saying "Unauthorized" on the screen. I tried going to /logout and /login and re-logged in, and still can't get past the Unauthorized step.

Sails seems to be throwing this error:

error: Sending 500 ("Server Error") response:
 Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)

I've tried shutting down and restarting both sails and the app and can't get any further.

I could theoretically run this on a linux box, but I'd have to run it more in a production-like method where it binds to the actual host instead of localhost. I'd have to connect from my web browser under windows. Is there an easy way to run in that method? This may isolate if its a windows-specific issue. Just a thought.

Thanks again for all the help so far!

**Comment by bfrey** [comment] 2017-02-10 17:12
Ahh! I put in an ugly hack in the sails.js portion, but this is just in a dev env currently so should be fine.

In app.js under sails, I added this line:
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

and the app came back!

**Comment by jchansen** [comment] 2017-02-20 09:02
@bfrey ack, I meant to respond to this like a week ago. I wanted to say thank you for filing this issue, and for being the catalyst for a great improvement to the Quickstart. There is now a repo with the finished code for the Quickstart (one repo for each language) along with links in each Quickstart step to check out the branch containing the finished code for that step.

### Windows Development
As for Windows development, I fixed my monitor issue and built the [ES6 version of the quickstart code](https://github.com/lore/lore-quickstart-es6) on Windows 10, to see if I would hit any issues. The only one I found was related to WebStorm (the IDE I was using) where it would lock up the project folder during development, and prevent npm from installing new packages. To resolve that I had to close WebStorm and then run the `npm install` from a cmd prompt, and then re-open WebStorm to continue development. Super obnoxious and strange for sure, but aside from that I didn't see any issues.

### Sails.js Error
I'm glad you were able to solve the Sails.js error. That's really interesting that you got that TSL error. I *think* I've seen that before (I can't recall exactly) but if I did, it was because I was using a self-signed SSL certificate for localhost development, but that's something I rarely do. I googled what the `NODE_TLS_REJECT_UNAUTHORIZED ` environment variable is associated with after you posted your solution, and that seems to be one reason you'd get that error (an invalid SSL certificate).

Most of the time during development I'm using HTTP connections, i.e. talking to the API through `http://localhost:1337`, and not HTTPS, i.e. `https://localhost:1337`. So if you were using HTTPS for development, that might make sense you got that error, but if not, then I'm stumped : (

### Linux on Windows
To be clear, I expect Lore to run well on Windows, and if it doesn't for some reason, it's a bug (provided the issue isn't the 260 character path name limit, though I think Microsoft is fixing that).

That being said, if you want to run Linux within Windows, I'm a big fan of Vagrant and the developer experience surrounding it, especially when it comes to port forwarding. They make it really easy to map Linux ports to Host ports (ie. what you'd type in the browser tab in Windows) and even cover it in their [Getting Started Tutorial](https://www.vagrantup.com/docs/getting-started/networking.html).

I should add the disclaimer that I've never used Vagrant in Windows (yet) but that would definitely be the first thing I (personally) reached for if I needed to.

### Issue Resolved / Closing
With the addition of the code repos, and the fact you solved your issue, I think this issue is resolved so I'm going to close it. But feel free to reopen it or create a new issue if you have additional questions. Thanks again!

**Closed by jchansen** 2017-02-20 09:02 UTC
